server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://18.233.255.172:3306/edusys_01?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: TianShui#2025!

# mybatis:
#   mapper-locations: classpath:mappers/*.xml

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
